//
//  keycodes.h
//  qmk-keyboard
//
//  Created by Barnaby on 2020-11-11.
//  © 2020 Barnaby Kendall. All rights reserved.
//

#pragma once


#define KC_LEFT_SINGLE_CURLY_QUOTE  RALT(KC_RBRACKET)
#define KC_RIGHT_SINGLE_CURLY_QUOTE RALT(KC_RIGHT_CURLY_BRACE)
#define KC_LEFT_DOUBLE_CURLY_QUOTE  RALT(KC_LBRACKET)
#define KC_RIGHT_DOUBLE_CURLY_QUOTE RALT(KC_LEFT_CURLY_BRACE)

#define KC_LSCQ KC_LEFT_SINGLE_CURLY_QUOTE
#define KC_RSCQ KC_RIGHT_SINGLE_CURLY_QUOTE
#define KC_LDCQ KC_LEFT_DOUBLE_CURLY_QUOTE
#define KC_RDCQ KC_RIGHT_DOUBLE_CURLY_QUOTE

#define KC_LSBS LSFT_T(KC_BSLASH)
#define KC_RSSL RSFT_T(KC_SLASH)

#define KC_EN_DASH      RALT(KC_MINUS)
#define KC_EM_DASH      RALT(KC_UNDERSCORE)
#define KC_NOT_EQUAL    RALT(KC_EQUAL)
#define KC_PLUS_MINUS   RALT(KC_PLUS)
#define KC_ELLIPSIS     RALT(KC_SCOLON)

#define KC_NDSH KC_EN_DASH
#define KC_MDSH KC_EM_DASH
#define KC_NOEQ KC_NOT_EQUAL
#define KC_PLMI KC_PLUS_MINUS
#define KC_ELIP KC_ELLIPSIS

#define KC_1PASS LGUI(LCTL(KC_QUOT))
#define KC_TOGGL LCAG(KC_F10)
