#pragma once

#define IGNORE_MOD_TAP_INTERRUPT

#define USB_MAX_POWER_CONSUMPTION 100

#ifdef BACKLIGHT_PIN
#undef BACKLIGHT_LEVELS
#define BACKLIGHT_LEVELS 8
#define BACKLIGHT_BREATHING
#endif

#define ENCODERS_PAD_A { F6 }
#define ENCODERS_PAD_B { F5 }
#define ENCODERS_KEY_LAYER { 8 }
#define ENCODER_RESOLUTION 3

#define RGB_DI_PIN D3
#ifdef RGB_DI_PIN
#undef RGBLED_NUM
#define RGBLED_NUM 5
#define RGBLIGHT_INDICATOR 5,1
#define RGBLIGHT_SLEEP
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_LAYERS
#define RGBLIGHT_MAX_LAYERS 10
#define RGBLIGHT_LAYERS_OVERRIDE_RGB_OFF
#define RGBLIGHT_LAYER_BLINK
#endif
