# Look for a JSON keymap file
ifneq ("$(wildcard $(MAIN_KEYMAP_PATH_5)/keymap.json)","")
    KEYMAP_PATH := $(MAIN_KEYMAP_PATH_5)
else ifneq ("$(wildcard $(MAIN_KEYMAP_PATH_4)/keymap.json)","")
    KEYMAP_PATH := $(MAIN_KEYMAP_PATH_4)
else ifneq ("$(wildcard $(MAIN_KEYMAP_PATH_3)/keymap.json)","")
    KEYMAP_PATH := $(MAIN_KEYMAP_PATH_3)
else ifneq ("$(wildcard $(MAIN_KEYMAP_PATH_2)/keymap.json)","")
    KEYMAP_PATH := $(MAIN_KEYMAP_PATH_2)
else ifneq ("$(wildcard $(MAIN_KEYMAP_PATH_1)/keymap.json)","")
    KEYMAP_PATH := $(MAIN_KEYMAP_PATH_1)
endif

# Load the keymap-level rules.mk if exists
ifneq ("$(wildcard $(KEYMAP_PATH))", "")
    -include $(KEYMAP_PATH)/rules.mk
endif

KEYMAP_C := $(BUILD_DIR)/src_$(TARGET)/keymap.c
KEYMAP_GEN_C := $(BUILD_DIR)/src_$(TARGET)/keymap_jsongen.c
KEYMAP_PARSED_C := $(BUILD_DIR)/src_$(TARGET)/keymap_parsed.c
KEYMAP_JSON := $(KEYMAP_PATH)/keymap.json
KEYMAP_PARSER := $(KEYMAP_PATH)/parse_keymap.awk


# Copy/concatenate parsed autogenerated file and optional extras into keymap.c
ifneq ("$(wildcard $(KEYMAP_PATH)/keymap_*.c)", "")
$(KEYMAP_C): $(KEYMAP_PARSED_C) $(wildcard $(KEYMAP_PATH)/keymap_*.c)
	/bin/cat $(KEYMAP_PARSED_C) $(KEYMAP_PATH)/keymap_*.c > $@
else
$(KEYMAP_C): $(KEYMAP_PARSED_C)
	/bin/cp -f $< $@
endif

# Optionally parse the generated key map
ifneq ("$(wildcard $(KEYMAP_PARSER))", "")
$(KEYMAP_PARSED_C): $(KEYMAP_GEN_C) $(KEYMAP_PARSER)
	/usr/bin/awk -f $(KEYMAP_PARSER) $(KEYMAP_GEN_C) > $@
else
$(KEYMAP_PARSED_C): $(KEYMAP_GEN_C)
	/bin/cp -f $< $@
endif

# Generate the key map C file from JSON
$(KEYMAP_GEN_C): $(KEYMAP_JSON)
	bin/qmk json2c --quiet --output $@ $(KEYMAP_JSON)
