#pragma once

#define VIAL_KEYBOARD_UID {0xA0, 0xB6, 0x93, 0x6B, 0xB9, 0x84, 0xAE, 0xE7}

#define VIAL_UNLOCK_COMBO_ROWS { 0, 0 }
#define VIAL_UNLOCK_COMBO_COLS { 0, 9 }

// Auto Shift
#define NO_AUTO_SHIFT_ALPHA
#define AUTO_SHIFT_TIMEOUT TAPPING_TERM
#define AUTO_SHIFT_NO_SETUP

#undef COMBO_COUNT

#define DYNAMIC_KEYMAP_LAYER_COUNT 5
#define DYNAMIC_KEYMAP_MACRO_COUNT 1
#define VIAL_COMBO_ENTRIES        12
#define VIAL_KEY_OVERRIDE_ENTRIES 12
#define VIAL_TAP_DANCE_ENTRIES     8

#undef  RGBLIGHT_MAX_LAYERS
#define RGBLIGHT_MAX_LAYERS (DYNAMIC_KEYMAP_LAYER_COUNT + 6)
