#pragma once

#undef MATRIX_ROW_PINS
#undef MATRIX_COL_PINS
#undef BACKLIGHT_PIN

#define MATRIX_ROW_PINS { GP15, GP14, GP29, GP13, GP12 }
#define MATRIX_COL_PINS { GP9,  GP3,  GP8,  GP7,  GP6,  GP5 }



#define IGNORE_MOD_TAP_INTERRUPT

#define USB_MAX_POWER_CONSUMPTION 100

#define BACKLIGHT_PIN GP10

#ifdef BACKLIGHT_PIN
//#define BACKLIGHT_BREATHING
#endif

#define ENCODERS_PAD_A { GP26 }
#define ENCODERS_PAD_B { GP27 }
#define ENCODERS_KEY_LAYER { 8 }
#define ENCODER_RESOLUTION 3

#define RGB_DI_PIN GP0
//#define RGB_DI_PIN GP16
#ifdef RGB_DI_PIN
#undef RGBLED_NUM
#define RGBLED_NUM 5
#define RGBLIGHT_ANIMATIONS
#define RGBLIGHT_SLEEP
#define RGBLIGHT_LAYERS
#define RGBLIGHT_MAX_LAYERS 10
#define RGBLIGHT_LAYERS_OVERRIDE_RGB_OFF
#define RGBLIGHT_LAYER_BLINK
#endif
